### ISSUE TITLE
Feature - Error message for selecting multiplie content axis

### ISSUE THREAD

**Issue by strand93** [hajke-gu/text-mod#126]

**Comment by HarFis** [comment]
<img width="308" alt="Screenshot at Oct 27 11-14-49" src="https://user-images.githubusercontent.com/43996812/97854754-2e5a3e80-1cfa-11eb-9ba4-c31ab44134bf.png">

**Comment by HarFis** [comment]
<img width="266" alt="Screenshot at Oct 27 11-14-31" src="https://user-images.githubusercontent.com/43996812/97854784-3619e300-1cfa-11eb-9be0-8fa3378fe4c0.png">
